services:
  db:
    image: mariadb:10.11
    container_name: django_db
    restart: always
    environment:
      MYSQL_DATABASE: gestion_bancaire
      MYSQL_USER: toto
      MYSQL_PASSWORD: toto
      MYSQL_ROOT_PASSWORD: toto
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - main_network

  nats:
    image: nats:latest
    restart: always
    networks:
      - main_network

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - nats
      - db
    networks:
      - main_network

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - nats
      - db
    networks:
      - main_network

  admin-worker:
    build:
      context: ./admin
      dockerfile: Dockerfile
    restart: always
    command: python manage.py listen_nats
    depends_on:
      - nats
      - db
    networks:
      - main_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - nats
      - db
    networks:
      - main_network

  client-worker:
    build:
      context: ./client 
      dockerfile: Dockerfile
    restart: always
    command: python manage.py listen_nats  
    depends_on:
      - nats
      - db
    networks:
      - main_network

  nginx:
    image: nginx:latest
    ports:
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - admin
      - client
    networks:
      - main_network

volumes:
  mariadb_data:

networks:
  main_network:
    driver: bridge